# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonviolent_number', models.IntegerField(default=0)),
                ('violent_number', models.IntegerField(default=0)),
                ('nonviolent_context', models.IntegerField(default=0)),
                ('violent_context', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zipcode_text', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 5', regex='^\\d{5,5}$')])),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecaster.ZipCode'),
        ),
    ]
